### 服务器配置
server:
  port: 8756

### TIMO配置
project:
  captcha-open: false                         #是否开启登录验证码
  shiro:
    remember-me-timeout: 7                    #cookie记住登录信息时间，默认7天（天）
    global-session-timeout: 43200              #Session会话超时时间，默认30分钟（秒）
  upload:
    #file-path: F:/upload/                    #文件上传路径，默认在项目根目录upload下
    static-path: /upload/**                   #上传文件静态访问路径

### spring配置
spring:
  ## 数据库配置vehicle
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://10.33.77.66:5419;DatabaseName=copy_chaosheng
    username: sa
    password: ss123$%^

  ## jpa配置
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: false
    open-in-view: true
    database-platform: org.hibernate.dialect.SQLServer2008Dialect

  ## thymeleaf模板设置
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
    mode: HTML
    encoding: utf-8
    servlet.content-type: text/html
    cache: false

  ## 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  ## json配置
  jackson:
    time-zone: Asia/Shanghai

upload-path: c:/image/
userPicture-path: c:/userPicture/
operationManual-path: c:/userManual/
apkVersion-path: c:/apkVersion/
#E-SOP 模具编号格式设置   奥飞需要加上AD
ESOPFormat: AD{0}-